---
settings:
  name: ONTAP tools for VMware vSphere 10.0
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 适用于VMware vSphere 10.0的ONTAP工具文档
    url: "/index.html"
  - title: 发行说明
    url: "/release_notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: manage
  - section: migrate
  - title: 法律声明
    url: "/legal-notices.html"
