---
permalink: concepts/concept_configure_vvols_datastores.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用适用于 ONTAP 的 VASA Provider 创建和管理 VMware 虚拟卷（ VVols\ ）。您可以配置，编辑，挂载和删除 VVOL 数据存储库。此外、您还可以向此虚拟卷数据存储库添加存储或从此虚拟卷数据存储库中删除存储、以提高灵活性。 
---
= VVOL 的 VASA Provider 配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用适用于 ONTAP 的 VASA Provider 创建和管理 VMware 虚拟卷（ VVOL ）。您可以配置，编辑，挂载和删除 VVOL 数据存储库。此外、您还可以向此虚拟卷数据存储库添加存储或从此虚拟卷数据存储库中删除存储、以提高灵活性。

一个FlexVol 数据存储库由一个存储容器(也称为后备存储)中的一个或多个VMware卷组成。一个虚拟机可以分布在一个 VVOL 数据存储库或多个 VVOL 数据存储库中。

虽然您可以创建包含多个FlexVol卷的Vvol数据存储库、但存储容器中的所有FlexVol卷都必须使用相同的协议(NFS或iSCSI)和相同的Storage Virtual Machine (SVM)。


NOTE: 最好在一个 VVOL 数据存储库中包含多个 FlexVol 卷，以提高性能和灵活性。由于 FlexVol 卷具有 LUN 计数限制，限制了虚拟机的数量，因此，包括多个 FlexVol 卷可以使您在 VVOL 数据存储库中存储更多虚拟机。添加不同的卷可提高数据存储库的功能、在这种情况下、可以混合使用精简卷和厚卷、以便可以在数据存储库上创建这两种类型的VM。

VASA Provider会在配置虚拟机或创建VMDK期间创建不同类型的VVOL.

* * 配置 *
+
VMware vSphere 使用此 VVOL 数据存储库来存储配置信息。

+
在 SAN （块）实施中，存储是一个 4 GB 的 LUN 。
在精简配置中、vCenter 8会将容量增加到256 GB LUN。

+
在 NFS 实施中，此目录包含 VM 配置文件，例如 vmx 文件以及指向其他 VVOL 数据存储库的指针。

* * 数据 *
+
此 VVOL 包含操作系统信息和用户文件。

+
在 SAN 实施中，此 LUN 与虚拟磁盘大小相同。

+
在 NFS 实施中，此文件的大小与虚拟磁盘的大小相同。

* * 交换 *
+
此 VVOL 是在启动虚拟机时创建的，并在关闭虚拟机时删除。

+
在 SAN 实施中，此 LUN 与虚拟内存大小相同。

+
在 NFS 实施中，此文件大小与虚拟内存大小相同。

* * 内存 *
+
如果在创建 VM 快照时选择了内存快照选项，则会创建此 VVOL 。

+
在 SAN 实施中，此 LUN 与虚拟内存大小相同。

+
在 NFS 实施中，此文件大小与虚拟内存大小相同。


